services:
  - type: web
    name: strava-mcp-server
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: STRAVA_ACCESS_TOKEN
        sync: false
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: STRAVA_REFRESH_TOKEN
        sync: false 
